name: Docker Image CI

on:   
  release:
    type:
      - released

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: telegram_clock
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      shell: bash
      run: |
        echo building image -\> ${DOCKER_USERNAME}/${IMAGE_NAME}:${GITHUB_REF##*/}
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker build --no-cache -t ${DOCKER_USERNAME}/${IMAGE_NAME}:${GITHUB_REF##*/} .
        docker tag ${DOCKER_USERNAME}/${IMAGE_NAME}:${GITHUB_REF##*/} ${DOCKER_USERNAME}/${IMAGE_NAME}:latest
        docker push ${DOCKER_USERNAME}/${IMAGE_NAME}:${GITHUB_REF##*/}
        docker push ${DOCKER_USERNAME}/${IMAGE_NAME}:latest